-- public.quiz definition

CREATE TABLE public.quiz (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar(255) NULL,
	CONSTRAINT quiz_pkey PRIMARY KEY (id)
);

-- public.question definition

CREATE TABLE public.question (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	value varchar(255) NULL,
	quiz_id int8 NOT NULL,
	CONSTRAINT question_pkey PRIMARY KEY (id)
);


-- public.question foreign keys

ALTER TABLE public.question ADD CONSTRAINT fkb0yh0c1qaxfwlcnwo9dms2txf FOREIGN KEY (quiz_id) REFERENCES quiz(id);

-- public.answer definition

CREATE TABLE public.answer (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	value varchar(255) NULL,
	question_id int4 NOT NULL,
	CONSTRAINT answer_pkey PRIMARY KEY (id)
);


-- public.answer foreign keys

ALTER TABLE public.answer ADD CONSTRAINT fk8frr4bcabmmeyyu60qt7iiblo FOREIGN KEY (question_id) REFERENCES question(id);
